---
- block:
  - name: "Open https and http ports in firewalld"
    firewalld:
      service: "{{ item[0] }}"
      permanent: yes
      state: enabled
      immediate: yes
      zone: "{{ item[1] }}"
    loop: "{{ ['http', 'https'] | product(['public', 'Campus', 'Bastions']) | list}}"
  - name: "Create /var/www/ if it doesn't exist"
    file:
      path: "/var/www/"
      state: directory
      owner: "{{ deploy_user }}"
      group: "nginx"
      mode: "0755"
  - name: "use acl to grant nginx access to all files in /var/www/, recursively"
    acl:
      path: "/var/www/"
      entity: "nginx"
      etype: "user"
      permissions: "rx"
      recursive: yes
      state: "present"
      default: yes
  - name: Create /var/www/html
    file:
      path: "/var/www/html/"
      state: directory
      owner: "{{ deploy_user }}"
      group: "nginx"
      mode: "0755"
    become: yes
  - name: "Grant deploy user user permissions to write to var/www/html using an acl"
    acl:
      path: "/var/www/html/"
      entity: "{{ deploy_user }}"
      etype: "user"
      permissions: "rwx"
      state: "present"
    when: deploy_user != None
  - name: "Set SELinux context for /var/www/html/"
    community.general.sefcontext:
      target: "/var/www/html(/.*)?"
      setype: "httpd_sys_content_t"
      state: "present"
  - name: "enable SELinux boolean to allow httpd to make network connections"
    seboolean:
      name: "httpd_can_network_connect"
      state: "on"
      persistent: true
  - name: "enable SELinux boolean to allow httpd to make network connections"
    seboolean:
      name: "httpd_unified"
      state: "on"
      persistent: true
  - name: "enable SELinux boolean to allow httpd to execmem"
    seboolean:
      name: "httpd_execmem"
      state: "on"
      persistent: true
  become: true